# Generated by Django 2.2 on 2020-10-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_one', models.CharField(max_length=20)),
                ('noun_two', models.CharField(max_length=20)),
                ('noun_three', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('adjective', models.CharField(max_length=20)),
                ('noun_four', models.CharField(max_length=20)),
            ],
        ),
    ]
