# Generated by Django 3.1.2 on 2020-10-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyone',
            name='story_name',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
