# Generated by Django 3.1.2 on 2020-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0002_storyone_story_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('silly_word1', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('illness', models.CharField(max_length=30)),
                ('noun_plural', models.CharField(max_length=30)),
                ('adjective1', models.CharField(max_length=30)),
                ('adjective2', models.CharField(max_length=30)),
                ('silly_word2', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('adjective3', models.CharField(max_length=30)),
            ],
        ),
    ]
