# Generated by Django 3.1.2 on 2020-10-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0003_storytwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytwo',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
