# Generated by Django 3.1.2 on 2020-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0005_storywar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryDragons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('superlative', models.CharField(max_length=200)),
                ('adjective1', models.CharField(max_length=200)),
                ('body_part', models.CharField(max_length=200)),
                ('noun1', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
                ('adjective2', models.CharField(max_length=200)),
                ('adjective3', models.CharField(max_length=200)),
                ('adjective4', models.CharField(max_length=200)),
            ],
        ),
    ]
