# Generated by Django 3.1.2 on 2020-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0006_storydragons'),
    ]

    operations = [
        migrations.AddField(
            model_name='storydragons',
            name='body_part2',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
