# Generated by Django 3.1.2 on 2020-10-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0007_storydragons_body_part2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryWalmart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('verb1', models.CharField(max_length=200)),
                ('adjective1', models.CharField(max_length=200)),
                ('noun1', models.CharField(max_length=200)),
                ('adjective2', models.CharField(max_length=200)),
                ('verb2', models.CharField(max_length=200)),
                ('verb3', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('adjective3', models.CharField(max_length=200)),
                ('noun2', models.CharField(max_length=200)),
                ('noun3', models.CharField(max_length=200)),
                ('noun4', models.CharField(max_length=200)),
                ('relative', models.CharField(max_length=200)),
                ('adjective4', models.CharField(max_length=200)),
                ('adjective5', models.CharField(max_length=200)),
                ('noun5', models.CharField(max_length=200)),
            ],
        ),
    ]
