# Generated by Django 3.1.2 on 2020-10-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0008_storywalmart'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryLoveLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('adjective1', models.CharField(max_length=200)),
                ('verb1', models.CharField(max_length=200)),
                ('part_of_the_body', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('noun1', models.CharField(max_length=200)),
                ('adverb', models.CharField(max_length=200)),
                ('verb2', models.CharField(max_length=200)),
                ('pronoun1', models.CharField(max_length=200)),
                ('person2', models.CharField(max_length=200)),
            ],
        ),
    ]
