# Generated by Django 3.1.2 on 2020-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0011_storygreetingsearthlings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HailToTheChief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('adjective1', models.CharField(max_length=200)),
                ('noun1', models.CharField(max_length=200)),
                ('noun2', models.CharField(max_length=200)),
                ('noun3', models.CharField(max_length=200)),
                ('noun4', models.CharField(max_length=200)),
                ('verb1', models.CharField(max_length=200)),
                ('verb2', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
            ],
        ),
    ]
