# Generated by Django 3.1.2 on 2020-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0012_hailtothechief'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayFestivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('holiday', models.CharField(max_length=200)),
                ('noun1', models.CharField(max_length=200)),
                ('verb1', models.CharField(max_length=200)),
                ('noun2', models.CharField(max_length=200)),
                ('verb2', models.CharField(max_length=200)),
                ('noun3', models.CharField(max_length=200)),
                ('noun4', models.CharField(max_length=200)),
                ('noun5', models.CharField(max_length=200)),
                ('noun6', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
            ],
        ),
    ]
