# Generated by Django 3.1.2 on 2020-10-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0013_holidayfestivities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayfestivities',
            name='noun6',
        ),
    ]
