# Generated by Django 3.1.2 on 2020-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0014_remove_holidayfestivities_noun6'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaParlor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('male_name', models.CharField(max_length=200)),
                ('adjective1', models.IntegerField()),
                ('noun1', models.CharField(max_length=200)),
                ('adjective2', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('noun2', models.CharField(max_length=200)),
                ('verb1', models.CharField(max_length=200)),
                ('liquid', models.CharField(max_length=200)),
                ('noun3', models.CharField(max_length=200)),
            ],
        ),
    ]
