# Generated by Django 3.1.2 on 2020-10-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0015_pizzaparlor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaparlor',
            name='adjective1',
            field=models.CharField(max_length=200),
        ),
    ]
