# Generated by Django 3.1.2 on 2020-10-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_time', '0018_baseball'),
    ]

    operations = [
        migrations.CreateModel(
            name='JJRTolkien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('fruit', models.CharField(max_length=200)),
                ('noun1', models.CharField(max_length=200)),
                ('noun2', models.CharField(max_length=200)),
                ('noun3', models.CharField(max_length=200)),
                ('noun4', models.CharField(max_length=200)),
                ('noun5', models.CharField(max_length=200)),
                ('noun6', models.CharField(max_length=200)),
                ('silly_word', models.CharField(max_length=200)),
            ],
        ),
    ]
